### ISSUE TITLE
v3 tag is not pointing to v3.0.0

### ISSUE THREAD

**Issue by ma575081** [tspascoal/get-user-teams-membership#28] opened 2024-02-26 20:45 UTC
The v3 tag was created/updated on Oct 1. The v3.0.0 tag was created on Oct 7.
So anyone using the v3 tag is not actually using v3.x.x.

**Comment by ponny-m** [comment] 2024-03-01 21:50
I think you are right since my updates to v3 (which includes node 20 upgrade) show the same error as the previous version. 
`Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: tspascoal/get-user-teams-membership@v3`.

**Comment by tspascoal** [comment] 2024-03-02 17:10
👋 @ma575081 @Ponnia-M Thank you for bringing this to my attention.

The issue is now fixed, v3 is pointing to v3.3.0 🚀

**Closed as completed by tspascoal** 2024-03-02 17:10 UTC

**Comment by ponny-m** [comment] 2024-03-10 20:04
Please upgrade the latest version from 3.0.0 (latest) to v3.3.0. I got this error when I upgrade this github action to v3.3.0: `Unable to resolve action `tspascoal/get-user-teams-membership@v3.3.0`, unable to find version `v3.3.0``

**Comment by tspascoal** [comment] 2024-03-11 19:09
@Ponnia-M No sure If I understand your request.

There is no version `v3.3.0`

Latest version is `v.3.0.0`



![Image](https://github.com/tspascoal/get-user-teams-membership/assets/7847935/1e002c92-a523-4f7b-9be5-ac4caa58ffde)

**Comment by ponny-m** [comment] 2024-03-12 18:07
My apologies. I misunderstood when you mentioned v3.3.0
